### ISSUE TITLE
Option to highlight text in Note

### ISSUE THREAD

**Issue by bhupesh-sf** [penge/my-notes#105]
Can we add an option to highlight some important items in the note with some color?

**Comment by penge** [comment]
Let me see. But I think we cold have that.

**Comment by penge** [comment]
Highlight is on a good way. Preview follows.

### Highlight & Un-Highlight a Text

![highlight_or_unhighlight](https://user-images.githubusercontent.com/907255/85805484-ba58ca00-b74c-11ea-9a6e-2cc1306239c6.gif)

### Highlight only parts of the word

![highlight_parts_of_the_word](https://user-images.githubusercontent.com/907255/85805604-115e9f00-b74d-11ea-8dce-026b6626b59c.gif)

### Highlight a paragraph or a sentence

![highlight_a_paragraph](https://user-images.githubusercontent.com/907255/85805646-2d624080-b74d-11ea-8738-8b02653b6a8c.gif)

I am really proud of this one. Especially handling some special cases, like highlighting multiple nodes with a different parent, inverting the highlight, or especially trying to highlight a selection that contains a combination of already highlighted and not highlighted.

It is implemented w/o dependency on `document.execCommand` so that's a win. Also it's implemented in a way, that the color (foreground color) but also background color, can be customized as you wish. Also, it doesn't mess up the other styles, they can be combined, look:

![highlight_combined_styles](https://user-images.githubusercontent.com/907255/85806050-4a4b4380-b74e-11ea-90bd-e766ad57ec53.gif)

**Comment by bhupesh-sf** [comment]
Awesome, great work :+1:

**Comment by penge** [comment]
Cool, thanks!

**Comment by bhupesh-sf** [comment]
@penge Trying Highlight but it doesn't seem to be working.

**Comment by bhupesh-sf** [comment]
@penge I just noticed its not working with custom theme. Following is my theme file:

`:root {

  /* Scrollbar */

  --scrollbar-track-background-color: #121212;
  --scrollbar-thumb-background-color: grey;
  --scrollbar-thumb-hover-background-color: #555;


  /* Generic */

  --background-color: #24292E;
  --text-color: #D6D8DA;
  --link-color: white;
  --svg-fill-color: #626262;


  /* Notifications */

  --notification-border-color: transparent;


  /* Overlay */

  --to-create-overlay-background-color: #134e82;
  --to-rename-overlay-background-color: rgba(30, 136, 229, .7);
  --to-delete-overlay-background-color: rgba(255, 0, 0, .6);


  /* Modal */

  --modal-background-color: #222;
  --modal-border-color: transparent;
  --modal-input-border-color: transparent;
  --modal-button-background-color: white;
  --modal-button-text-color: #121212;


  /* Context menu */

  --context-menu-background-color: #626262;
  --context-menu-text-color: white;
  --context-menu-border-color: transparent;


  /* Sidebar */

  --sidebar-notes-background-color: #1B1D23;
  --sidebar-notes-text-color: #D6D8DA;
  --sidebar-active-note-background-color: #222;
  --sidebar-active-note-text-color: #FFF;


  /* Drag */

  --drag-border-color: #454545;
  --drag-resizing-border-color: white;


  /* Bar */

  --bar-border-color: #1B1D23;


  /* Toolbar */

  --toolbar-button-color: #626262;
  --toolbar-button-hover-background-color: #222;
  --toolbar-button-hover-color: white;


  /* Only in Options */

  --hotkey-background-color: #222;
  --hotkey-text-color: white;

  --comment-background-color: #222;
  --comment-text-color: white;

  --slider-background-color: white;
  --slider-thumb-background-color: white;
  --slider-thumb-size: 12px;
}

body {
  opacity: 1;
}`

**Comment by penge** [comment]
I replied you here, I hope that helps https://github.com/penge/my-notes/issues/113#issuecomment-651023071
