### ISSUE TITLE
Allow setting any note as the "Clipboard" note

### ISSUE THREAD

**Issue by kankaristo** [penge/my-notes#134]
Continuing from https://github.com/penge/my-notes/issues/132#issuecomment-705535821.

Right-clicking on a note could show an option like "Use as clipboard", which would set that note to receive text from the My Notes context menu. The clipboard note cannot be deleted or renamed, or the context menu functionality would break.

Allowing the user to set any note as the clipboard note would effectively allow renaming the current note named "Clipboard".

This would also potentially allow using a different note as the clipboard on different computers, which would make it easy to sync text between computers without "mixing" the clipboards (unless you set all computers to use the same note as the clipboard).

**Comment by penge** [comment]
This is definitely a great idea. Note could be set to have a Clipboard role (only one note could be having this role) so it can receive the text as well.

There could be some visual hint (icon or color) so the user quickly knows which note serves as a Clipboard (because it could be named from now on differently).

In computer A and B, different notes could take on this role. If on a receiving computer there would be no such note, a Clipboard could be automatically created for that purpose, so the text can be received. Then, Clipboard could be renamed, or even deleted and other note could be set as a Clipboard.
