### ISSUE TITLE
Add shortcut key for Sync? 

### ISSUE THREAD

**Issue by RobColes** [penge/my-notes#135]
Would be helpful if there was a shortcut key for the Sync, especially for when the sidebar is hidden.

**Comment by penge** [comment]
Sounds good. The shortcut can be added.

As the Sidebar would be hidden in this case, the Sync button (spinning when in progress) could be shown for a moment or some other information, to show that the Sync is in progress or that it has successfully finished.

**Comment by kankaristo** [comment]
I would love for this to be Ctrl+S, since I find myself naturally pressing Ctrl+S to save, which currently toggles the sidebar (which could be moved to e.g. Ctrl+B for "sideBar").

But some users might be annoyed if Ctrl+S was switched to do something else than what it did previously.

**Comment by penge** [comment]
@kankaristo definitely a great input. I see Sidebar as a much more common shortcut, and was therefore thinking about adding:
`Ctrl + Shift + G` where G stands for Google / Google Drive. What do you think?

**Comment by RobColes** [comment]
FWIW I'm with @kankaristo, but I'm new to My Notes. Ctrl-S is pretty universal in the windows ecosystem for Save. Ctrl-B for sidebar also works well for me.

If this isn't possible, better for me to be Ctrl and one letter than Ctrl-Shift-something - they are hard with one hand. Maybe Ctrl-Y for sYnc if Ctrl-S doesn't work.

Love the software!

**Comment by penge** [comment]
Thanks Rob!

Yeah, Ctrl - S is universal for saving. Here, things are autosaved.

Here's another proposal: (vote 👍 )

```
Ctrl + B    Toggle Sidebar
Ctrl + E    Toggle Toolbar
Ctrl + S    Sync notes
```

If you'd like Ctrl + Shift + G and keep the Ctrl + S for Sidebar, vote 🚀

**Comment by penge** [comment]
@kankaristo and @RobColes Unfortunately guys Ctrl + B cannot be used as it serves as a shortcut for **"Bold"**. I completely forgot about that for a moment. But we'll figure it out.

Here's a list of Chrome shortcuts, we can find something suitable:
https://www.computerhope.com/shortcut/chrome.htm

Shortcuts for Windows and OSX will be improved, where they will be separate (not interchangeable by switching Ctrl with Cmd, etc.) The reason is, in some cases there are different default shortcuts for Windows and OSX, as well their behavior, or conflicts that could occur. Therefore they will be separate.
