### ISSUE TITLE
Chenge sync icon when there are unsynchronized changes

### ISSUE THREAD

**Issue by pato7** [penge/my-notes#139]
It might be useful to somehow indicate that there are unsaved changes in the notes, so the users would be encouraged to synchronize the notes.

**Comment by penge** [comment]
Hi pato, This is a great suggestion. Thank you! I will think about improving this.

**Comment by penge** [comment]
There's no easy way to tell if there are some remote notes updated, meaning this icon could only tell you if local notes are not yet saved to Google Drive.

Would you like to see this feature?
What the icon should be if all is synced? Something like we have in Google Docs? That is Cloud with a little tick inside?

**Comment by penge** [comment]
I had a working example. After local changes were synced, **"Sync now"** icon was changed to **"Cloud done"** icon. At first, it looked ok.

There were some issues:

- Since last sync, remote changes (made in Google Drive directly, or through other My Notes) can be made. That means, **"Cloud done"** icon would NOT be true.
- Moving mouse over **"Cloud done"** icon could change it back to **"Sync now"** icon, as I may need to pull remote changes (relates to previous point). Changing the icons back and forth didn't look nice.

For these reasons, I've decided to close.
