### ISSUE TITLE
Buttons block scroll bar

### ISSUE THREAD

**Issue by MichaelWehar** [penge/my-notes#16]
When the scroll bar appears, the buttons (for dark mode & font size) appear over top of it.

Ideally, the buttons should be to the left of the scroll bar.

**Comment by penge** [comment]
I will look at it today. Thanks for finding.

**Comment by penge** [comment]
@MichaelWehar I have checked the behavior, and it's actually on both, light & dark mode.

I have found the cause and it's a tricky one. Because by solving one, I may compromise the other.

**I need to decide what's more important.**

A) either the fact the scrollbar **squeezes** a bit when going to the very bottom, or,
B) allowing text to **overlap** the buttons (settings), which would solve A
Also, would need to put settings a bit further inside, that might not be as visually pleasing. Need to consider that different browser might have different scrollbar width.

**Conclusion.**
Scrolling works, the visual indication is still there (it squeezes it). The issue is, it's not 100%. I have a working prototype at the moment. 
This will need some more feedback before making the final decision.

**What can help.**
Now, need to look at it, decide, if it looks better, or not.
Are you up to try it locally before publishing?
I'll create a branch for it.
The manual installation instructions are in README.

**Comment by MichaelWehar** [comment]
I'd be happy to demo this if you have a separate branch for it.

Just reply via comment with the details and I'll give it a try.

**Comment by penge** [comment]
@MichaelWehar 

**I'll be back in about an hour.** 

I will get the branch here for you.
You may then download the ZIP, unzip at your computer and try in Chrome.
If all good. If UX Good. It can go to the next version.

**Comment by penge** [comment]
Hi @MichaelWehar 

Here's the branch => https://github.com/penge/my-notes/tree/scrollbar

Follow the **Install** instructions.

Let me know how it works for you.

Ideally, get 1+ opinion on this.

If all good. Can go to release.

**Comment by penge** [comment]
@MichaelWehar 

Time is up. **I am merging this.** I believe, you would agree too.
