### ISSUE TITLE
Sync My Notes Files with GitHub Repositories

### ISSUE THREAD

**Issue by theo-armour** [penge/my-notes#182]
It would be great if:

My Notes files may be synchronized with folders and files held in a GitHub repository 

Benefits
- Use My Notes open source tools to write to a Git versioning system
- Directly edit files available on the web via GitHub Pages
- Access files using the GitHub API

User input GitHub required:
- user name
- repo
- branch
- path
- GitHub access token

Given the above input, files hosted on GitHub may be updated with a simple XMLHTTPrequest or Fetch.

I can make a demo if needed.

**Comment by penge** [comment]
Sounds interesting. Not sure just where exactly this would fit. Simple pages I suppose. As Jekyll or other static site generators would not be suited for this.

DEMO would be really nice!

**Comment by theo-armour** [comment]
@penge 

Will code

**Comment by theo-armour** [comment]
@penge 

Please have a look at 

https://jsfiddle.net/theo/2azktLex/

Concept: Open from and save files to GitHub repositories using the GitHub API and simple JavaScript

Plus

Saving user inputs such as the Access Token using local storage

Requires a GitHub Access Token. See https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token.

Fingers crossed, this works for you. ;-)

**Comment by penge** [comment]
@theo-armour 

I have tested it and works perfectly. Thanks a lot!

What do you think would the benefit compared to editing the file directly on github?

**Comment by theo-armour** [comment]
@penge 

>> What do you think would be the benefit compared to editing the file directly on github?

* All the benefits that you have when you can sync to Google but not use Google Docs. ;-)
* Plus the benefits of GitHub
    * Access to Git
    * Open data formats
    * Accessible API  
* Access to a My Notes left menu file navigator that can significantly reduce clicks when you need to process multiple documents
* Access to an interactive HTML editor and previewer instead of Markdown
* Access to easier stylesheet support
* And more

**Comment by penge** [comment]
Thank you. I had to ask, as I think writing this down (as much as possible; even if sounds simple) is really helpful for following reasons. Others can see what it's about and share an opinion, we can decide what the first version should provide, see what future versions should provide, and how to approach things from the beginning.

From my point of view, I see a single biggest benefit in the git itself – history, branches (versions), collaboration. Using GitHub to store the notes sounds nice.

What I see as some downsides – using token with no expiry (as a password); token has to be stored; setting up token and other fields (user, repository, branch) is not as simple or convenient as clicking a button (compared to Google Drive Sync, or some OAuth flow).

How this could be integrated:
- there is an option to select/configure each store (Google Drive, GitHub)
- notes in the Sidebar are (a) grouped by the store (as in a directory), or (b) visible only from the one currently active store
- notes are separate in local store (because there are multiple stores), so the don't clash
- every store implements necessary methods to provide the same common functionality (list notes, pull notes, push notes) and a common (extracted out) conflict resolution (pulled note already exists with the same name, pulled note exists with a different name, etc. – this is already done in Google Drive Sync so it just needs to be put out)

I hope this comes useful to push this forward.

**Comment by theo-armour** [comment]
@penge 

>> as I think writing this down (as much as possible; even if sounds simple) is really helpful...

Me too. "Open source" is good. "Open development" is even better 

>> biggest benefit in the git itself...

For sure. Plus I find the GitHub cloud much easier to deal with than all the Google Drive thingis

>> downsides – using token with no expiry (as a password); token has to be stored; setting up token and other fields 

Currently the token, user, repo, branch etc are kept in localStorage. So the only big issue is that data needs to be re-entered on each new device.

All the rest

I will have a demo with a full left menu listing every folder & file in the repo up for you to look at in the next few days.

When that is up we can really start talking, er, writing things down. ;-)

**Comment by penge** [comment]
> Currently the token, user, repo, branch etc are kept in localStorage. So the only big issue is that data needs to be re-entered on each new device.

This doesn't have to be an issue, as Chrome Storage Sync (https://developer.chrome.com/docs/extensions/reference/storage/) can be used to deliver the same settings to the new device (if same Google Account is used) when needed. This sync storage is as of now used to transfer the text to other computer when My Notes Context menu is used.

Sounds great regarding the demo. Thanks a lot for help. I will try to specify down a common interface, that any store would implement to its own.
