### ISSUE TITLE
Not Showing on Shortcuts

### ISSUE THREAD

**Issue by AgostinhoRenner** [penge/my-notes#205]
After some update the **My Notes extensions** doesn't appear on the Shortcuts menu - _chrome://extensions/shortcuts_

Not sure if was the Browser update or the My Notes Update.

My Chrome Version: 89.0.4389.90 - 64 bits
My Notes Version: 3.6.0

**Comment by penge** [comment]
You are right. I have checked it and it happens in version 3.6.1, for me. Haven't experienced it in 3.6 though. Used the same Chrome version.

What is new in version 3.6.1, is moving to Manifest V3 (more at: https://developer.chrome.com/docs/extensions/mv3/intro). This is quite new. Available since Chrome 88.

Later while writing this message:
I have actually been able to just recover this feature. With the transition to Manifest V3, I have now tried to explicitly specify the shortcut, and it was successfully added to the page. Explanation:  Manifest V3 is a probably a bit more strict in this.
Good news is, we can give the shortcut a nice caption (instead of "Activate the extension" something more readable like "Open My Notes"), and we can even make the shortcut global if preferred. That would mean you could open My Notes with a shortcut even if no Chrome is open, yet.

Sending some screenshots how it looked in version 3.6, and how it could look in a next patch where this would be fixed.

### 3.6

<img width="706" alt="3_6" src="https://user-images.githubusercontent.com/907255/112202515-c1e0cd00-8c11-11eb-88bc-cd751b11bfd9.png">

### Upcoming patch

<img width="706" alt="next_1" src="https://user-images.githubusercontent.com/907255/112204114-99f26900-8c13-11eb-9fb9-b3a3a1d23438.png">

<img width="706" alt="next_2" src="https://user-images.githubusercontent.com/907255/112204127-9d85f000-8c13-11eb-9f4b-4d8b89381c68.png">
