### ISSUE TITLE
Synced the wrong way? Pulled old Google Drive info to replace current My Notes 

### ISSUE THREAD

**Issue by Questionsonly** [penge/my-notes#206]
Hi, 
It looks like My Notes synced in the wrong direction when I clicked to sync. It's updated my current (march 23) note to replace it with March 16 version. Is there anyway to go back to what it was before the sync?

**Comment by penge** [comment]
Hi,
I am sorry to hear this. Actually it shouldn't happen as the newer version (from Google Drive, or from My Notes) should be used. In case there was some conflict (file edited both in Google Drive and My Notes since the last sync), it should merge two files together instead of overriding one.
Have you maybe edited the note in Google Drive at some point? Or was the note edited only in My Notes?
What you could try, it to check Google Drive, where you should be able to see some file history, I hope it will be there. Here's a screenshot what to look for in Google Drive:

<img width="345" alt="Screen Shot 2021-03-23 at 20 14 54" src="https://user-images.githubusercontent.com/907255/112205995-b5f70a00-8c15-11eb-8598-0e4db8648e97.png">

How to find this:
1. Open "My Notes" folder in Google Drive.
2. Select the note you would like to look at in history.
3. Click on Info icon (as in above screenshot) which should be in the top right, that should give you access to "Activity" (is History) and see the file at different times.

Let me know if this helped.

**Comment by Questionsonly** [comment]
Thank you so much! No, this didn't help, sadly. 
The note document in GDrive shows it was last modified on March 16 - and that's the version that was restored on My Notes browser today. It's so sad! This is the first time anything like this has happened. I hadn't edited the Note in Gdrive in a long time so that's not the issue.

**Comment by penge** [comment]
I am really sorry. Would like to get to the root of this. I think there had to be something unexpected about the file, or some series of steps, that led to this. Did it happen also before or after, or just once?
I can try to replicate the same steps/scenario on my computer, that could help to find the fix.

**Comment by Questionsonly** [comment]
It's just happened once. I clicked on the SYNC button — that was the only step. Also, only the main/Clipboard note was affected in this way. 
Is there a limit to the number of Notes one should use? I'm currently using 20+ Notes. Many of them are quite long. Could that the causing issues?

**Comment by penge** [comment]
Thank you. That will help a lot and I'll look on Clipboard sync.
There is no limit for the number of notes, but there is limit for their total size – 5MB (limit of the browser). Although that should be enough, can be reached quickly if inserting embedded images (directly as the content and not as links) or a lot of text.
There is one issue regarding this (https://github.com/penge/my-notes/issues/144) that also discusses how this limit could be increased to unlimited. Something I would like to add in near future.

**Comment by Questionsonly** [comment]
Thank you! Please let me know if I can offer more information! This is a great extension so I'm happy to help!

**Comment by penge** [comment]
Happy to hear that! What do you btw think about following change/improvement? It is about opening My Notes with Ctrl+T or Ctrl+N. More about it is here:
https://github.com/penge/my-notes/discussions/208 and https://github.com/penge/my-notes/issues/204#issuecomment-805780719

**Comment by penge** [comment]
I've been able to reproduce the prolem. Working on a fix.
