### ISSUE TITLE
Add support link

### ISSUE THREAD

**Issue by skinnedpanda** [penge/my-notes#252]
Why not add this to encourage users to support the development of this great extension. It's suttle.

![Buy me a cofee](https://user-images.githubusercontent.com/34305307/120935288-4f589700-c702-11eb-8a78-a357c5543d68.png)

**Comment by penge** [comment]
Thank you for a nice suggestion!

I have to say I am pretty reserved in this, My Notes is currently shy in credits – and it probably shouldn't. I always wanted to add only what is related to the functionality, never compromise the experience or the UI, or push user into something, or create some sort of obligation/expectation from the user. It is not why I am doing this. I just want to create something useful.

On the other hand, I am very grateful to everyone who bought me a coffee and I definitely had one after that :) Wondering how things would change after adding the link, maybe I would have a lot of coffee.

What I think definitely could be added, is **Name and Email** in the credits area. Not only it could improve trustfulness in the extension, but also serve as the fastest way to get support or share feedback. In this section, **Buy me a coffee link** could be added. Let's say in the Notifications popup as well. I will provide some screenshots so we can review them. Sounds good?

**Comment by skinnedpanda** [comment]
I think that is noble of you, but in my opinion there is nothing wrong with asking to get sponsored from volunteers. Altruism is a great concept, but it doesn't necessarily give us what we need to help others. It's like what they say on safety briefs on airplanes, "put your own mask on first, before helping others," else you might be incapacitated by hypoxia.

I like your suggestions.

**Comment by penge** [comment]
Thank you for eyeopening words. It makes sense, I agree.

I have prepared some screenshots:

<img width="622" alt="Buy me a coffee" src="https://user-images.githubusercontent.com/907255/121094083-552ba680-c7ee-11eb-9b1b-6d7474cf94a1.png">

<img width="723" alt="Buy me a coffee 2" src="https://user-images.githubusercontent.com/907255/121094097-58bf2d80-c7ee-11eb-8768-14b074a1f205.png">

Details:

- My name is an email link. It can be used to get support or share feedback. I will use the same email as on [extension's page](https://chrome.google.com/webstore/detail/my-notes/lkeeogfaiembcblonahillacpaabmiop) under "Contact the developer". I find it important to match. The email won't be listed in the repository, rather than set before making the build for Web Store, but I guarantee to be it my email.
- Tried to use a coffee cup icon, but removed it after all as the official icon from https://www.buymeacoffee.com did not match Dark theme, or Custom theme. So it was either official icon, or none. I was thinking using a different icon could make it a little bit suspicious as after user would be redirected to https://www.buymeacoffee.com, he would see a different icon. So if the icon wouldn't match after all or would be different, I decided to to use one, and just make it a regular link.

I think this could be fine. What do you think?

**Comment by skinnedpanda** [comment]
Yes, I like it. Having your full name there makes it personal.

Why not just use an emoticon as coffee cup? ☕ works with dark and light themes. There are some badges could work with dark theme on [this page](https://www.buymeacoffee.com/downloads).

**Comment by penge** [comment]
To be honest, I would probably not add any link if it would have to be with emoji. I know it may sound strange but I dislike the idea of adding anything that pops out more than text around, especially if not used daily.

Some other reasons why I would not prefer to put emoji, is that it looks different on different browsers, it can change line height (this coffee emoji does). I think I received first coffee when it wasn't even in the documentation, just metioned somewhere in the older issue before it was added to the documentation. So I woudn't be worried as there's always option to visit Homepage and look for ways to sponsor.

**Offtopic:**

I was thinking now about maybe writing some premium content on Buy me a coffee, some short posts and snippets on things. Like how to create first extension in 5 minutes. What are the APIs. What is a service worker. How to handle messaging between different frames. Why Typescript is better. Just a thought. Not sure what would be the interest for these kinds of posts. Some kind of microblog it could be.

**Comment by skinnedpanda** [comment]
I will read your microblog. Wouldn't mind learning how to make extensions that help me automate mundane, everyday tasks.

**Comment by penge** [comment]
@skinnedpanda 

Feel free to share what kind of things you'd like to automate and if you don't mind they could be the basis to write a step-by-step series on how to create such extension (aka learn by example). We could even put it on Web Store at the end.

**Comment by skinnedpanda** [comment]
@penge 

I'll give it some thought. What first came to mind was a robots.txt reader that alerted the user. Then I found two such extensions in the store. Funny.

**Comment by skinnedpanda** [comment]
![image](https://user-images.githubusercontent.com/34305307/122641080-43f26c00-d103-11eb-9901-6d0edf431c9d.png)
Looks great! I hope you get more coffee.

**Comment by penge** [comment]
I actually got 2 coffees today, it works! 🙂 You were right 🙂

**Comment by skinnedpanda** [comment]
That's great. When I drink too much coffee, I get jittery. Some people can drink lots of coffee before they go to sleep. I've never understood that. I would be bouncing off the walls all night long.

**Comment by penge** [comment]
Same for me. I started to cut down on coffee recently and have to say I am feeling more productive. My productivity is more stable and uninterrupted for longer periods of time. Although several coffees or even redbulls would bring inital burst of energy, it was usually followed by some crash or several unproductive days, so in the long run it was less productive.
