### ISSUE TITLE
Add option to customize Toolbar position

### ISSUE THREAD

**Issue by hematinik** [penge/my-notes#256]
Hello!
I think it is better to position the toolbar on the top of the editor to make the interface more intuitive and standard. I also suggest making the buttons a little larger
```
#toolbar, #sidebar-buttons {
    font-size: 1em;
}
```
I've also added 

```
body.with-toolbar #toolbar {
    border-bottom: 1px solid gray;
}
```
this is how it looks:
![Screenshot_20210613_153244](https://user-images.githubusercontent.com/38541836/121804637-9d1e5380-cc5c-11eb-8cf7-ab0521daf3c1.png)
- - -
as a feature request  my-notes lacks option to change the font size . it could be achieved using a shortcut or the toolbar menu.

p.s
sorry Im not a git professional, next time I'll make pull requests.

**Comment by penge** [comment]
Hi!

Thank you for your suggestions! We could do following:

**Toolbar position**
I will add option to Options page to customize the Toolbar position. Options will be: Top, Bottom. I will leave Bottom as default, for now, but anyone can change it to Top at any time.
I agree having it at the Top, is more familiar in content-rich editors, Microsoft Word, Google Docs, etc. Therefore having that option is definitely welcome. Thanks!

**Larger Toolbar/Sidebar buttons**
When I looked at the note's text, I wanted to achieve that Toolbar/Sidebar buttons are just a little bit smaller to that so in the grand scheme of things they are almost not there, or they don't seem more important than the note's text, or they don't pull my eyes away from the content, or distract me. I'll try to do something about it. I think having it as option added to Options page, would make everyone happy. Some might give it 0.8, some 1.0 and some 1.5. I had email request where 1.5 was actually the best fit.

**Font size**
There could be new controls added just like in Word, these are Font Size, Grow Font, Shink Font.
![image](https://user-images.githubusercontent.com/907255/121810868-b32f1280-cc62-11eb-8e6d-d7939032568b.png)

**Comment by hematinik** [comment]
sounds good! as an Idea maybe you could couple the icon size setting to the `Size` slider so we can change the overall Interface font size just by one value. Im not sure if this is a good Idea but I look at it this way:
we will have 3 preset buttons instead of an Integer slilder: [Small][Medium][Large]
you can change the overall sizing using predefined settings, say the Small option sets the interface's font size to 0.8em, the Medium sets to 1em and Large to 1.5em. there could be more fine-tuning under the hood for example you may find the 0.8em too small for the Side Bar so the small would be 1em for that component.

**Comment by penge** [comment]
Yes, I would give it General size slider that would set the size for everything – that's what we have now.
On top of that, I would add Icons size slider that would set icons size <ins>**relative**</ins> to general size, that could be from 80% up to 200%.
I think instead of having two possible ways to set things, that is either 3 presets or using the slider, I think it's better to keep only one way to do it. I'd like to hide details like 0.8em, 1em, 1.5em completely, and rather show percentage or something easy to grasp. Using sliders prevents from typing some bad values as well, so not only user woudn't have to think about what 0.8em is, but also he cannot set it to some wrong value, thus sliders.

About font size dropdown, that would be a different thing and there would be some specific numbers to set the size, as being exact and consistent is more important. Sliders in Options would be more based on the feeling what is right for me, no need to know if my setting turned out to be 0.8em or 1.2em or other.

**Comment by penge** [comment]
@hematinik 

Soon there will be My Notes 3.10 and it will have Command Palette, Lock/Unlock for notes, and also larger icons, they will be 1em as you suggested :)

**Comment by hematinik** [comment]
wow can't wait for it! Im reading the codebase trying to get familiar with the project, yet I may help by doing something other than coding If you wish, like research, etc...

**Comment by penge** [comment]
I think you helped a lot already, by sharing your feedback. Any help like the research or anything you enjoy doing would be very appreciated.

**Comment by hematinik** [comment]
Im glad to hear that! all I can do for now is to promote my-notes, currently I have no particular Idea to make it any better :)

**Comment by penge** [comment]
That is more than enought. Thanks! :)

**Comment by penge** [comment]
That is more than enough. Thanks! :)
