### ISSUE TITLE
my-notes starts with "Disabled" google drive sync

### ISSUE THREAD

**Issue by hematinik** [penge/my-notes#267]
I'm sorry to report that there seems to be a minor problem related to the sync, when I open a new my-notes tab the "Enable Google Drive Sync" option is set to "Off" by default and I have to re-enable the option in order to Sync.

also when I edit a note in offline-mode, the sync process appends the Cloud version to the end of the note as soon as the sync gets enabled.

I just discovered that we are facing a complex problem, Im trying my best to describe it:

1- each my-notes tab starts with "Disabled" Google Drive Sync
2- If I have made some changes inside a specific note when offline, the sync process appends the Google Drive version at the end of the note whenever I "Enable" the sync
3- having multiple my-notes tabs open at the same time doubles the confusion because the "Enable Google Drive Sync" is not globally set (I assume)

maybe I could help if you describe the Sync algorithm, but from what I can conclude the "Sync - In" function gets called every-time that I enable the option, no matter if the both versions (offline/cloud) are Identical. I think we should compare the edit timestamps or just using a git like "diff" to compare notes?

![Screenshot_20210620_154752](https://user-images.githubusercontent.com/38541836/122672294-20e9ba00-d1e0-11eb-8d91-e9b47091e3e2.png)

- - -
P.S
I get some weird errors/issues in the console which I'm not sure if they are related to the problem:

![Screenshot_20210620_151001](https://user-images.githubusercontent.com/38541836/122671053-23491580-d1da-11eb-8493-aa987f1371eb.png)

**Comment by penge** [comment]
First and foremost — Thank you very much for the detailed description and the included screenshots! It helped a lot!

<br>

**"Indicate whether to send a cookie in a cross-site request by specifying its SameSite attribute"**
The default behavior for cookies is changing (more at https://web.dev/samesite-cookies-explained/). As writing this reply I have looked into it and solved it. The solution was to add a **host permission** for `https://drive.google.com/` that makes cross-origin requests to this domain trusted. Google Drive is where our images are uploaded and then served from.
<ins>Resolution</ins>: **Solved.** Expect in version `3.9.2`.

<br>

**`net::ERR_FILE_NOT_FOUND`**
This is a common error when a requested file is not found (in our case png image). It can happen if you try to use **Insert image** modal and insert an image by a URL that doesn't exist. I would try to look inside a note if there isn't some missing image.
<ins>Resolution</ins>: Standard browser behavior. No action needed.

<br>

**1**
I would try to enable **Google Drive Sync** and see if the problem continues. I have made a change that on start checks if any optional permission was removed or not. In case it was, and it was **"identity"**, Google Drive Sync is disabled.
But this is something that should almost never happen. What I usually do during the testing, I reload (on and off) the extension for 10, 20, maybe 30 times, to try out edge cases or just to see if handlers are properly attached between the restarts (browser restart, extension restarted). I found out, that permission is sometimes due to these many restarts removed. In that case, I wanted to uncheck **Google Drive Sync** in Options, to do the cleanup after the removed permission.
<ins>Resolution</ins>: Try to enable **Google Drive Sync** and see if the problem continues.

<br>

**2**
If you disable **Google Drive Sync**, edit some note, and then enable **Google Drive Sync** at some point, **Google Drive Sync** will first see there is an existing file for that note (they have the same name), and then it will compare if note and file have **the same last modified time**. If they do, note and file are simply connected. If they don't, file's content is added to the end of the note's content. Even if note would be newer (more recent last modified time), file could be edited while **Google Drive Sync** was disabled. There is no easy way to tell if the file content can be replaced, or it was edited and has some important content. To not lose what was in the file, file's content is added to the note. When Google Drive Sync is not disabled, synchronization continues as expected.
<ins>Resolution</ins>: It's probably alright.

<br>

**3**
If note is edited in 1 tab, it is updated in others. If note is updated through **Google Drive Sync**, it is updated in every open tab.
<ins>Resolution</ins>: It's probably alright.

<br>

---

**How Google Drive Sync works:**

Changes are first **pulled**, then **pushed**.

**Pull:**
1. Deletes notes that were not modified since their file was deleted from Google Drive.
2. Creates notes for every new file in Google Drive where note with that name doesn't exist yet (there's no conflict).
3. Updates notes for every updated file in Google Drive, or connects notes to existing files (initial sync).

**Push:**
1. Creates a file for every new note.
2. Updates file for every updated note.

**Comment by penge** [comment]
**Further explanation:**

There are 3 ways how Google Drive Sync can be stopped/disabled:

1. User action - user unchecks **"Enable Google Drive Sync"** in Options. I think we can dismiss this reason in this issue. User action is also the only way how to request optional permission, more about that here:
https://developer.chrome.com/docs/extensions/reference/permissions/#step-3-request-optional-permissions
2. Google Drive Sync configuration is reset between version updates, or it's not migrated. This is not the case, I have checked there is no migration needed for this configuration, which is stored under the key **"sync"**. Migration is needed only if backward incompatible changes would be made to the configuration, and thus if not migrated, new version would not know how to handle it and reset would be suggested.
3. Chrome decides it's time to request the permission again. It seems that this can be the case. Recently, I have added a code that checks if the necessary permission (called **"identity"**) is still given on every start. If it is, all continues. If it was removed, I react to that event by unchecking **"Enable Google Drive Sync"** option and disabling the "Sync now" button. Here is the code that manages this:
https://github.com/penge/my-notes/blob/master/src/background/init/permissions.ts#L37-L44
It seems that before this optional permission called **"identity"** could be removed by the browser as well, there just wasn't action for that event to reset the related UI when the permission is no longer granted. The easiest way to spot that the permission is still granted or not, is by seeing the "Sync now" button enabled or disabled.
