### ISSUE TITLE
Auto Sync failed

### ISSUE THREAD

**Issue by skinnedpanda** [penge/my-notes#291]
I lost a lot of notes I've been taking for the last week. Last successful sync was 29 July, which is correct looking at the time stamps on the files in Google Drive.

In Developer Tools I got this message as it tried to sync.
![image](https://user-images.githubusercontent.com/34305307/128403922-52d9a92a-d357-4349-ad79-607fdc1aaaf5.png)

**Comment by penge** [comment]
This error happens when you exceed 5MB limit for the notes.

It can be solved by adding a new permission for unlimited storage. If user agrees, My Notes could go beyond 5MB.

This permission should required (opposite to optional) as to prevent any problems with reaching the limit.

What do you think?

The solution for you now, would be to check how big is the folder in Google Drive, and temporarily move aside notes that are too big or make total size above 5MB. Till unlimited permission would be in place.

**Comment by skinnedpanda** [comment]
A good idea to let the user have a choice about it. Perhaps have it warn the user when approaching the limit too. I don't know many users would need more than 5 Mbytes of notes... but then again, engineers back in the days never thought a computer could possible use more than 512 kbyte of RAM - they they came up with _expanded_ and _extended_ memory.

**Comment by penge** [comment]
5MB seems enough and unlimited storage if added, should probably be optional. Keeping as many things as possible optional might be more challenging to do but in the end user has the full control over it.
