### ISSUE TITLE
Not allowing text color change

### ISSUE THREAD

**Issue by Alexbba** [penge/my-notes#318]
Windows 10, desktop Lenovo Ideacenter 3:
Certain times/places (don't ask me where/when), cannnot change text color.
MORE: Upon reloading page, allows me to change one more selected text item, selected manually by moving cursor to start of a word, and using shift+right arrow to highlight text (using double click to highlight the word won't allow color change button to work/respond!), but beyond that single selected item, stops working again and need to reload to allow me one more change again. BUT sometimes when reloading, allows no color change, and sometimes two changes!

See screenshots.

![image](https://user-images.githubusercontent.com/62662548/134822666-8fc0ce53-4e6f-4d2f-897b-48915a8c929c.png)

![image](https://user-images.githubusercontent.com/62662548/134822730-021ad363-51f1-416d-b183-86a2a24f8203.png)

**Comment by penge** [comment]
Hi @Alexbba,
From what I read it seems there is more than just one problem.
I have tried changing text color now, it worked for me well.
There is one situation, where this might NOT work, that is when you copy & paste some text with formatting (like from a website), in which case it can insert this text with inline styles (that define font type, size, and color) and these have higher priority => reason why changing text color might not work.
There might be other reasons we don't know about yet. As you say, certain times it doesn't work. If inserting some text with formatting (from website or other source) was something you done before, that can be the reason. For other reasons, it needs to be tested and exact steps will need to be found out, in order to fix. I'll try to look at it and text some scenarios if I can find something out.

**Comment by arunmehra2k16** [comment]
I am facing the same issue. I have not copied and pasted the text; rather everything has been typed. Here is what I have observed:

- Highlighting any text (even if it is a single word) with the mouse pointer and then trying to change the text color DOESN'T WORK
- Highlighting any text using Shift+End or Shift+Home and trying to change the text color DOESN'T WORK
- Highlighting any text using Shift+Arrow (Right or Left) and trying to change the text color WORKS
- Highlighting more than one line using Shift+Arrow (Right or Left) and trying to change the text color DOESN'T WORK

I am on Windows 10, Toshiba laptop, core i5.
