### ISSUE TITLE
Lost Visibility to Separate MyNotes Tabs/Clipboards

### ISSUE THREAD

**Issue by geoffcg123** [penge/my-notes#334]
Last week I lost the ability to see my separate Clipboard categories in the Left-hand side of "MyNotes" extension
The MyNotes Extension loads with only the most recent Clipboard that I had accessed "Two" the extension url link loads ending with html?note=Two 
I can access the other Clipboards if I swap out the "Two" for other labels I used like "One", "Test" etc, directly in the URL - so they are not lost, just not easy to access. 

I closed all my browsers, and cleared cached and cookies, but it still only loads the one clipboard.
if it's user error, can someone please offer a suggestion.
<img width="744" alt="Screen Shot 2021-12-17 at 3 22 12 PM" src="https://user-images.githubusercontent.com/49886429/146618727-d5afb6c6-f212-49d9-aa2b-5f385e45a5c6.png">

**Comment by geoffcg123** [comment]
I ended up copying and pasting all my notes into word doc, removed the extension and re-added it, and it reset back to the original experience - the option to toggle between separate Notes, "Options" and "Create New Note" came back.
Not sure what happened, but I'll just copy and paste it all back in. 
<img width="657" alt="Screen Shot 2021-12-17 at 3 43 06 PM" src="https://user-images.githubusercontent.com/49886429/146620024-8c8ccaaa-7e05-494d-bfb4-d16813d07532.png">

**Comment by penge** [comment]
Hi @geoffcg123,

Let me reply to your both comments.

**To your latest comment:**
When extension is uninstalled, Chrome will also erase all data related to it and stored in the browser. Exporting notes or making other backup is suggested. I am glad you did. Unfortunately, uninstalling chrome extension cannot show a warning (or be otherwise interrupted) that would inform about this behaviour.

**To you first comment:**
It seems there is something preventing Sidebar to show. I believe there could be some steps to replicate that problem. If that problem would occur again (meanwhile I will try to replicate it), please try to look into Chrome Console, if any error (message in red) appears there on a page refresh. To show Chrome Console, see menu Chrome / More Tools / Developer Tools / Console. This error message (if any) could help to find out the source of the problem.

**Comment by geoffcg123** [comment]
Okay thank you Pavel, if it occurs again I will follow your guidance
