### ISSUE TITLE
Keep UI buttons when hiding sidebar

### ISSUE THREAD

**Issue by anddam** [penge/my-notes#363]
Hiding the sidebar currently removes `#new-note` `#open-options` `#sync-now` buttons from UI.

Please keep those into the UI by moving `#sidebar-buttons` from its `#sidebar` parent into `#toolbar` as sibling of current `.topmenu.bar`.

**Comment by penge** [comment]
When the Sidebar is hidden and you don't see the notes list, creating a **new** note and knowing which note is currently open, becomes problematic. That's why I chose to hide the icon.

Options can be opened with `Cmd/Ctrl + Shift + O`. I hid the icon as I think it's not essential to see the icon at all times.

Sync can be done with `Cmd/Ctrl + R`. Sync should have the notes list visible as this action can change the list.

I like when **B** (Bold icon) is alligned with the content. If we would choose to show the Sidebar icons when the Sidebar is hidden, **B** icon wouldn't be aligned with the content. And I'd like to be consistent about that - to be aligned. Sidebar icons are not part of content, so I hid them.

I don't see a strong reason to keep those 3 icons visible. I am open to talk about this idea more and make some changes though.

**Comment by penge** [comment]
I just had an idea we could show all three icons left to the info icon (last icon), when the sidebar is hidden. I'd like to keep B (Bold) icon the first.
