### ISSUE TITLE
[feature request] Move current line up and down with keyboard modifier

### ISSUE THREAD

**Issue by anddam** [penge/my-notes#369]
A feature I constantly use in editors is using a modifier (usually Alt) and up/down arrow to move current line up and down by one line.

I am no *webster* at all but a quick look ad MDN says this would handle the job:

    function keyHandler(event) {
        if (event.keyCode==38 && event.altKey) {
            console.log('move current line up');
        } else if (event.keyCode==40 && event.altKey) {
            console.log('move current line down');
        }
    }
    document.getElementById('content').onkeydown = keyHandler;

An extended goal would be to move the current selection up and down altogheter.

**Comment by penge** [comment]
Thank you @anddam for the suggestion.
It is something we could definitely have for the plaintext notes (coming soon) as they would be much easier to work with (compared to the html notes) because having regular line breaks. Moving lines would easy to have there. The only complicated thing would be finding out (and keep track of) what line you are currently at, either you got to one with a keyboard, or clicked with a mouse.

I'll have a look at "move lines" for the html notes as well and see how that goes. It would be just moving html blocks in this case. I see this could be done in several stages (from easiest to hardest):
1) Move a line in plaintext notes
2) Move multiple selected lines in plaintext notes
3) Move one html block in html notes
4) Move multiple selected html blocks in html notes

**Comment by anddam** [comment]
>The only complicated thing would be finding out (and keep track of) what line you are currently at, either you got to one with a keyboard, or clicked with a mouse.

I am not sure to understand that part.

>I'll have a look at "move lines" for the html notes as well and see how that goes.

Is this someone editing _rich_ text (or HTML) is even interested in?

**Comment by penge** [comment]
Closing for now as I don't know how this would fit (at the moment, can revisit). By having this feature, we would lose default behaviour of these shortcuts or, switching between one or other behaviour seems too much. Need to think about this.

**Comment by adab4d** [comment]
I'll try and have a try at a PR proposale after raw mode gets out.
