### ISSUE TITLE
Open-tabs sync is behind the latest changes

### ISSUE THREAD

**Issue by FirebrandCoding** [penge/my-notes#37]
After typing the note, I would open a new tab again, to see if my changes have been properly saved. Most of the time, the aren't. Often enough, latest-added words phrases are missing, and I can't be sure they will be saved properly once I close the tab I was editing in.

It would be excellent if I could jot the notes down and close the tab, knowing full well that everything I'd left on the "page" is safe with the extension.

**Comment by penge** [comment]
Hi @FirebrandCoding

I understand your concern. I will soon release a next version (in 2 or 3 days) that will address this behavior and show in new tabs the most recent representation of what is, or more precisely will be, saved.

## How it works

Here's how the notes are saved and also an explanation on what's causing the described behavior.

Notes are saved **once per second** at most. That is at most 60 times per minute. At most because there is a following optimization.

If the time since last change (written text) is less than 1 second (happens very often during typing), changes are saved later, after 1 second of inactivity. **This is the reason why in new tab you see the outdated version, a version that will be saved shortly after.** You can try opening new tab in 1 or more seconds.
This is something that will be resolved in the next version.

In case the text is pasted and the tab is closed within 1 second, changes are saved before closing.

The reason for this saving strategy (1 time per second, at most) is because of the limit described in [documentation](https://developer.chrome.com/extensions/storage) which is 120 write operations per minute.

**My Notes** are stored in **Chrome Sync** that allows to see and edit notes across your devices. More on this topic is in this article: https://www.groovypost.com/howto/sync-chrome-across-all-devices/

## Next version

In next version, new tabs will show the most recent representation of what is, or more precisely will be, saved. More changes are listed here: https://github.com/penge/my-notes/milestone/5

Behind the scenes, saving will continue to happen 1 time per second, at most.

Expect the new version in about 2 or 3 days.

**Comment by FirebrandCoding** [comment]
Excellent. Glad to hear you're so close to a new version. Best of luck in development!

**Comment by penge** [comment]
@FirebrandCoding 

This behavior is now resolved. The feature list is complete and milestone 2.0 near its completion.

**Next steps:**
- further testing
- adding a screenshot(s)
- tweaks if necessary

The next version should be published in a day or two.
If you'd like to be notified, send a message to my email (in profile) and I'll let you know.
