### ISSUE TITLE
Put as Default New Tab in Google Chrome when opening new tab.

### ISSUE THREAD

**Issue by arita37** [penge/my-notes#373]

**Comment by penge** [comment]
This feature was removed in the past. It was **_optional_** (could be enabled/disabled via _Options_). Due to being **_optional_**, there turned out to be issues (slow, seeing a default New Tab page or bookmarks for a brief moment) that I coudn't solve. There is other possible approach to this which does <ins>not</ins> cause any of the issues, but it is not making the feature **_optional_**, which I found quite important to have.
