### ISSUE TITLE
[Queries]Save URL to remotely open My Notes & context menu for images

### ISSUE THREAD

**Issue by onlytanmoy** [penge/my-notes#393]
Hi mate, just now sent a small amount your way, hope you enjoy your Coffee 😊 Thanks for all the hard work.

Just got 2 queries:
a) In the latest version I see an option in the context menu as 'Save URL to remotely open My Notes', please explain what is that and how do I use it?

b) I was wondering like how we now have the option to save URL to any note, can the same be done for images too? As in I will right click on the image I intend to save and then from the context menu send it any note of my liking?

**Comment by penge** [comment]
Hi :)

Thank you for the support, very appreciated! :)

Regarding the queries:
a) "Save URL to remotely open My Notes" (URL) and "Save to remotely open My Notes" (selected text) can be used to save content to My Notes <ins>_open_</ins> in other computer(s). This allows easy text-transfer between two computers using My Notes.
My Notes on other computer(s) will received the content into a special note named **@&ZeroWidthSpace;received** (created automatically if it doesn't exist, otherwise updated). More at [Context menu](https://github.com/penge/my-notes#context-menu).

b) This is actually a great idea! I looked into it right away and can confirm this can be added. **Suggestion:** We have some special notes like @&ZeroWidthSpace;clipboard (quickly reachable first item in Context menu for general content), or @&ZeroWidthSpace;received (to receive content sent from other My Notes), and I was thinking about **_introducing a new kind of special note_** for this feature named **@&ZeroWidthSpace;images**, as a quickly reachable <ins>SECOND</ins> item in Context menu to quickly store images.
<ins>FIRST</ins> item would remain @&ZeroWidthSpace;received for consistency. Then, followed by all other notes, then, finished by "Save image to remotely open My Notes". In the end, all 3 Context menu usecases (save URL, save text, or save image), would behave similarly. What do you think?

**Comment by onlytanmoy** [comment]
Thanks for the clarification on point a.

I am glad you liked point b and yes I agree with your suggestion around that, cheers mate 👍
