### ISSUE TITLE
Context Menu not saving

### ISSUE THREAD

**Issue by dvnbld** [penge/my-notes#408]
Beautiful extension, but it sends any information from Context Menu (URL, Selected Text) to notes if "My notes" opened in background

**Comment by penge** [comment]
Hi, would you like to limit what information is coppied and what not?

**Comment by dvnbld** [comment]
Copying selected text, url and image works great, but with strange behavior) It`s not working at all if "My notes" haven`t opened, previously. It looks like that is a bug with inactive service worker.

To be sure that information is copied i found a way to make it work - just repeat action.

**Comment by penge** [comment]
Service worker switching itself to **"Inactive"** when not being needed (to free up resources), but then occasionally NOT being able to restart itself (set as Active) when being needed again, for example to handle My Notes Context Menu, is some odd behaviour I've been trying to figure out since Manifest version 3 (just for comparison, pernament background scripts in Manifest version 2 didn't suffer from this because they were running all the time). Haven't found how to solve it. Maybe Chrome issue?

**Comment by penge** [comment]
I will keep investigating this and at it seems there's nothing I can do about it, I hope there will be a solution for it soon. Closing now.
