### ISSUE TITLE
Feature to save the notes online?

### ISSUE THREAD

**Issue by jmaicaaan** [penge/my-notes#53]
I lost my notes yesterday and not sure what happened. Maybe because of the new update yesterday Jan 30? What I did was to reinstall the plugin again. Do you think in cases like this, we should be able to save it online instead of local storage?

**Comment by jmaicaaan** [comment]
Btw, love this tool!

**Comment by penge** [comment]
Hi there!

Did you uninstall the plugin and installed it again?
Or have you just received the update and it was gone?
Or have you open notes from other than main computer? (This behavior is changing now, read below)

This is how it works now: (since 2.2)
- Notes are stored locally in the current computer only
- To transfer some notes to other computer, a selection of text followed by using the context menu would work (the menu is called Save selection to other devices). There are some requirements:
  - logged into same Google Account (also required before)
  - the other machine is online and My Notes are open (this was not required before)

This is how it worked before: (before 2.2)
- All notes are stored online
- All notes can be viewed from other computer, even if turned on later

This sounds like a better experience was before 2.2. At a first sight, yes.

The change that 2.2 brings, is necessary. The reason is that the limit of online storage used before, called Chrome Sync, is only 8 KB per item, or 100 KB in total. This could cause problems in storing the notes once the limit is reached.

2.2 continues to use Chrome Sync only to send small pieces of information between computers, using the content menu as described.

All notes are stored locally now (even those received with content menu), in Chrome Storage Local. This storage has a limit of 5MB which should be more than enough. It is possible to change the limit to be unlimited (hard drive limit) if the extension would require that permission. At this point, I think 5MB is enough for text so the extension works in those limits.

You mentioned reinstalling the plugin. In such case the data would be wiped. This would apply to both local storage (Chrome Storage Sync) and online storage (Chrome Storage Sync or just Chrome Sync).

An independent online storage like Google Drive could be best. I check this one.

I am really glad you like the extension. I will continue to make it better! Thanks for the feedback.

**Comment by penge** [comment]
I've done some research on this and the easiest although not available option (as it works for Chrome Apps only, not Chrome Extensions) is, using the **Chrome Sync Filesystem API**. As said, this option is not applicable to Chrome Extensions and besides that Chrome Apps are being discontinued anyway.

The other option would be to create a trusted server that would be a part of **OAuth 2.0** authentication/authorization sequence. After user would be authorized and permissions would be granted to create a backup in **Google Drive**, My Notes could manage the backups for itself.

The managing costs for the second option would not be for free, although not any high though as it could be done serverless.

**Comment by jmaicaaan** [comment]
Hi,

Apologize for the late reply.

I think Google Drive is probably OK but if the cost is not worth it and not free. I don't think it's good if only a single person is requesting for the feature. I think it's still better to stick within the Google infrastructure but I'm wondering what are the other options you've seen besides from it? Any outstanding? Thank you for the support on this one! I use it on my day to day :)

**Comment by penge** [comment]
Hi,

No worries.

I think some kind of backup or export/import could be nice. Google Drive might be a bit out of reach at the moment but what can be done now is this:

- Manual export that would save all the notes into a zip file
- Manual import that would read a zip file and import the notes

This could be an intermediate step before having automated backups eventually (stored to Google Drive) but as it can be useful even after then, it could stay alongside the automated backups.

**Comment by penge** [comment]
Hi,

No worries.

I think some kind of backup or export/import could be nice. Google Drive might be a bit out of reach at the moment but what can be done now is this:

Manual export that would save all the notes into a zip file
Manual import that would read a zip file and import the notes
This could be an intermediate step before having automated backups eventually (stored to Google Drive) but as it can be useful even after then, it could stay.

**Comment by penge** [comment]
Hi,

No worries.

I think some kind of backup or export/import could be nice. Google Drive might be a bit out of reach at the moment but what can be done now is this:

- Manual export that would save all the notes into a zip file
- Manual import that would read a zip file and import the notes

This could be an intermediate step before having automated backups eventually (stored to Google Drive) but as it can be useful even after then, it could stay.

**Comment by jmaicaaan** [comment]
I just had a thought today. Do you think it is possible to prompt the user before uninstalling the plugin if they want to do a manual backup? In that way, users are notified/reminded that they will lost all their files but they can be backup. I hope that's not too much of a work to do. But anything can work for me. I'm down to have one instead of none 👌

**Comment by penge** [comment]
I'd like that. Unfortunately it is not possible due to security reasons. Uninstallation cannot be interrupted by prompt or call to action. It actually makes sence as this kind of control could potentially be misused to prevent the uninstallation.

**There are the remaining options:**

<ol type="A">
  <li>Manual export/import</li>
  <li>Automated backups</li>
</ol>

As I see it, manual is not something that someone would like to do. Unless transferring data to another computer. There is also a con in not having the most recent backup, which is kind of against the purpose.

On the other hand, **Automated backups** would beat manual backups in every way. Reasons:

1. It is up to date
2. It is saved to Google Drive; can benefit from revisions (can see previous version if needed)

I will check Google Drive further although the running woudn't be for free. Something that could be justified if the extension is priced (with a free trial). But, I am not sure if anyone pays for a software nowdays. Except for Office and Spotify 😃

**Comment by jmaicaaan** [comment]
A manual backup is probably OK but not really ideal. I agree with what you said, users don't really like to backup something and that would let the user manage the backups also by themselves which most of the cases, they don't like.

I hope there are still some alternatives that are free. Still hoping! 😄

**Comment by penge** [comment]
A **free** alternative would be if I pay B from my pocket 😬😄

**Comment by jmaicaaan** [comment]
Haha, not really expecting that one 😄but yeah, if most people request it, then I think it's great to go with the priced extension (with a free trial). 😄

**Comment by penge** [comment]
**Unlimited free trial** 🤣

**Comment by penge** [comment]
Get Ready. Having some good news 😁

<details>
  <summary>Click me :D!</summary>
  I tried Google Identity API 😲 and it works!! 😄

  <details>
    <summary>Click me too :DDDD!</summary>
    Version 3.0 is in the works now 💪
  </details>
</details>

**Comment by penge** [comment]
Get Ready. Having some good news 😁

<details>
  <summary>Click me :D!</summary>
  I tried Google Identity API 😲 and it works!! 😄

  <details>
    <summary>Click me too :DDDD!</summary>
    Version 3.0 is in the works now 💪
    (Google Drive support)
  </details>
</details>

**Comment by jmaicaaan** [comment]
Oh man that's really great news! Can't wait to see it in action 🔥

**Comment by penge** [comment]
Providing some info how it can work:

<br>

### Step 1

My Notes 3 is installed, see Options page for a new section **Google Drive**

<br>

### Step 2

Specify how would you like to **name your backup**
_Some examples: home, work, My Mac, etc._
_Why is it needed:_
- _to identify your backup easily (it will be created under Google Drive / My Notes / \<name of your backup\> folder)_
- _to be able to use different backups on different computers of yours while using the same Google account (but you can also decide to use the same backup on different computers, to keep the notes on different computers in sync)_
- _to list your backup(s) by their name to be able to chose an existing backup to connect to, or rather create a new backup (something that you can decide about when you reinstall My Notes, or install on a second computer)_

<br>

### Step 3

Click **Enable Google Drive backups**
_What would happen next:_
- _a prompt where My Notes as an extension would need an additional permission_
- _a consent screen where Google Cloud My Notes would need a permission to access Google Drive_

_This setting can be remembered on version updates_

<br>

### Security

_Optional permission required by My Notes can be granted only on user gesture like click on a button_
_The name of the permission is **identity** and is required to get access token_
_My Notes would remove this permission if user disables Google Drive backups_
_My Notes in Google Cloud would request a permission (via consent screen) where it can only see and manage its own files_

**Comment by jmaicaaan** [comment]
What happened to the comment on how it works 👀 haha

**Comment by penge** [comment]
I have to say this loud.

How painful it is to publish an extension:

- published only during working hours in California

- never published on weekends

- sometimes it takes days (Thursday, Friday, Saturday, Sunday, Monday)

- not in control how the required permissions are presented (like you want to open My Notes in a new tab, but the extension is presented like it can read browsing history)

- cannot publish new version if having a pending review (like you wait days for 2.3.1 to be published, and still need to wait for that first, but also, you need to quickly publish 2.3.2 which is long time ready)

<br>

I've published 15 versions of My Notes and what I described I experienced every single time.

My best intentions where I want to be transparent, or describe everything in detail, are just ruined by Google.

I will create the comment again. It will have probably many updates so just scroll up to see them.

**Comment by penge** [comment]
My Notes 3 will bring backups to Google Drive, here's how to enable it:
<br><br><br>

## Step 1

Open **Options**

<br>

## Step 2

Scroll to **Google Drive** and click **Backup My Notes to Google Drive**

<br>

## Step 3

Grant **permissions** to start the backups

<br><br><br>

That's it! 🙂

<br><br><br>

The permissions:

- My Notes will require your aprovall to use **Identity API** (https://developer.chrome.com/apps/identity) which will be used to get access token

- My Notes will show a consent screen where it will require your approval to access Google Drive

**Comment by jmaicaaan** [comment]
> I have to say. **How painful it is to get the extension published:**
> 
> * published only during working hours in **California** 🐻
> * never published on **weekends** 😡
> * sometimes **it takes days** (Thursday, Friday, Saturday, Sunday, Monday) 💀
> * not in control how the required permissions are presented (like you want to open My Notes in a new tab, but the extension is presented like it can read browsing history) 😔
> * cannot publish new version if having a pending review (like you wait days for 2.3.1 to be published, and still need to wait for that first, but also, you need to quickly publish 2.3.2 which is long time ready) 😔
> 
> 
> I've published 15 versions of My Notes already and what I described I experienced every single time.
> 
> My best intentions are just ruined by Google.
> 
> 
> I will create the comment again 😁👍
> 
> ⬇️ ⬇️ ⬇️

Ooohh, that's annoying. Never thought publishing an extension would be that hell of a ride. I thought it was just a simple like publishing on NPM. Well, that's why you deserve a ⭐️ ! Great work! Really looking forward to the next versions.

I was actually happy this morning when I opened my browser, it shows my notes which are quotes to help myself get reminded 👌

**Comment by penge** [comment]
So happy to hear that mate !!!! 🙂👍

<br>

NPM is definitely better here. I would prefer to take the same kind of responsibility in Web Store, claim what the extension does, and publish it at any moment, and again, **TAKE THE RESPONSIBILITY FOR IT.**

<br>

Because Google:

- when I provide a fix to something and it takes days to be published, it can look like I don't care 🤷‍♀️😴

- when I say the extension is for taking notes, but it is claimed as it reads browsing history, it's just terrible to fight against...

<br><br>

🕘

It is now **9 PM** in California. And I know I have to wait another at least **15 hours** to see **My Notes 2.3.2** published or not. This Monday. Maybe Tuesday. I can do nothing about it 😔

I am shocked there's no 24/7 when it comes to Google. This is just ridiculous 😃

**Comment by penge** [comment]
I am excited to announce that My Notes 3 will be using **JS modules** (https://v8.dev/features/modules)  under the hood, which is a native feature since **Chrome 61**.

This aims to provide better structured code, reusability if needed, separation of concerns.

I am against using Typescript or Webpack with Babel, if it's not really necessary, but more importantly, I'd like to distribute My Notes as is, in a readable form, further unprocessed, without any transpiling or minifying which would hinder the code.

At this moment, I have already made a successful transition to **JS modules** and from now on I am focused on implementing **Google Drive**.

Feel free to see the branch https://github.com/penge/my-notes/tree/next where you can at any point drop a comment if you'd like, if something is not understood well. As a part of My Notes 3, I am adding more comments to the codebase so you, or contributors, can get around easily.

🙂👍

**Comment by jmaicaaan** [comment]
Yeah, I feel you but I think for now we can't do anything about it. The best thing we can do is just be transparent in the README section or description. I think that's the best thing for now.

Glad to hear on the `next` of My Notes! Actually last night I was thinking of something... Like we have this page and we can toggle it from the lower right to switch pages. I thought of something like instead of having 3 pages of notes. Can we switch it to multiple notes? See attached image for some of my late night thoughts yesterday 😅 

![image](https://user-images.githubusercontent.com/13105222/74693486-ffad3e00-5226-11ea-89a8-01fc2db49879.png)

**Comment by penge** [comment]
**Love it!** Especially the effort! 🙂

<br>

## Switch

I like this one the most so I will start with it.

It could look like this:

```
Type your notes here.




____________________________
Options                    1


1
- current page number, but can also be a name (if renamed)
- on click, My Notes area is replaced with pages to choose from
```

And after I would click on page **1**:

```
1 Type your notes here.
2 Here I got something.
3 Buy milk. Buy coffee.


____________________________
Options                    1


1, 2, 3
- are displayed in a list
- every page is having a preview text (limited up to 50 characters)
- if you click on a page number (or name), it is open
- if you double click on page number (or name), you can rename the page
    and confirm its new name with either Enter or click outside,
    where if you try to set an empty name, it will be changed back
- "Type your notes here" would have lighter color so you know it is empty
- keyboard shortcuts would open page by their order (1, 2, or 3)
```

I think this could be it and it's pretty nice. Simple and provides some new functionality:

- preview of page
- renaming pages
- jump to any page

Right now, changing page might be faster but I wound't say it is better. It comes with some flaws:
`1 => 3` or `2 => 1` or `3 => 2` requires two clicks and if done as separate buttons, it is confusing and brings miss-clicks. Keyboard shortcuts would remain the fastest way.

This **Switch**, I like it.

<br>

## Image copy

Here, I am not sure what it would be. So, I cover some cases:

1. Copy image to My Notes text => I am not planning this
2. Copy image to Google Drive => Not really
3. Copy image to some folder in My Notes => Not really too :D

<br>

## MD support

Maybe in future :)

<br><br><br>

**btw:** Here's my Slack if you'd like to try 🧠⛈️ 😄 **https://bitly.com/hellopenge**

**Comment by penge** [comment]
# Preview

![Screenshot 2020-02-19 at 12 12 13 AM](https://user-images.githubusercontent.com/907255/74760235-ae479200-52ac-11ea-815d-c7d8d949ae6e.png)

- pages in bottom right
- current page underlined
- click to change the page
- double click to rename the page

**Comment by penge** [comment]
# Google Drive

![Screenshot 2020-02-19 at 12 17 05 AM](https://user-images.githubusercontent.com/907255/74760574-33cb4200-52ad-11ea-873d-acedea206de9.png)

**Comment by penge** [comment]
# Roadmap

### 2.4

- Anounce Google Drive
- Use JS modules

### 2.5

- Page switcher
- Rename page

.
.
anything that comes up
.
.

### 3.0

- Google Drive

**Comment by penge** [comment]
![Screenshot 2020-02-19 at 12 33 35 AM](https://user-images.githubusercontent.com/907255/74761977-8dcd0700-52af-11ea-9fe6-5138dcb16909.png)

**Comment by penge** [comment]
@jmaicaaan would you like to see optional feature (enabled in Options page with a checkbox) that would everytime you open My Notes, scroll down and put the cursor at the end, so you can start typing?

**Comment by jmaicaaan** [comment]
@penge - Hi!

Regarding the new design for the switch. I was thinking of something like Google Doc style that acts like cards. Not sure how hard that could it be. But I can offer help designing that in my spare time 😄 I like to try developing with some extensions as well!

For the option of Google Drive, I think we can just disable the checkbox if it's toggleable at the moment. Haha, but not really big deal! Wooo excited for that backup 😄 

What does the optional feature mean? Not very sure I do understand how it works hehe

**Comment by jmaicaaan** [comment]
Really excited about the upcoming ones! 🎉

**Comment by penge** [comment]
haha 😄 nevermind, that feature doesn't make much sense to me as well, won't be used

Those **tiles**, I was thinking about it, woudn't fit into the design (if redesigned in future, might look that way).

I decited to use list because:

- simple
- minimize mouse movement (short distance)
- preview text won't be necessary if page has a name

I hope that's fine 😁👍

**Comment by penge** [comment]
I am not even half way through the prototype and I have to say tiles are f$kncng incredible **:D**

Soon screenshot here.

**Comment by jmaicaaan** [comment]
Really! Love to hear you still did try it! Weee! 👍

**Comment by penge** [comment]
## Tiles

![tiles](https://user-images.githubusercontent.com/907255/74825389-6b34ff80-533c-11ea-82d4-50c4a4db7c11.png)

😁👍

**Comment by jmaicaaan** [comment]
Moving my tile comment on the linked issue!! 😁

**Comment by penge** [comment]
The main post if this thread is https://github.com/penge/my-notes/issues/53#issuecomment-586792839

**Comment by penge** [comment]
The main post in this thread is https://github.com/penge/my-notes/issues/53#issuecomment-586792839

**Comment by penge** [comment]
_Implemented. Closing. Proceeding to testing._

**Comment by penge** [comment]
@jmaicaaan I think you were interested in **Image copy**. Check this: **https://github.com/penge/my-notes/issues/74**

Using the dropdown menu to Copy/Paste will work the same as keyboard shortcuts, like `CTRL+C` and `CTRL+V`.
