### ISSUE TITLE
Elaborate on permissions required to use the extension

### ISSUE THREAD

**Issue by FirebrandCoding** [penge/my-notes#60]
It seems that the new version of My Notes was disabled because it required another permission: to read my browsing history – something I wouldn't think necessary for a new-tab note-taking extension.

Could you elaborate on the permissions required by the extension? Something like "Replace new tab" would make sense on its own – it is, after all, decidedly a new-tab replacement extension – while browsing history access raises a bit of a concern.

**Comment by penge** [comment]
This is really stupid. I am pissed about Web Store as there is no way to test the publication before eventual publication = which means no dev Web Store environment.

The newly added permission is called **"tabs"**. This is defined in `manifest.json`. This persmission is required to replace a new tab programatically which is defined in `background.js`, whereas before it was done declaratively in `manifest.json`.

I can now see by installing it from Web Store that the interpretation really sucks. Not only it is interpreted as `It can: Read your Browsing history` which is total bullshit but also the review process is zero. There is literally nothing in the code that has something to do with Browsing history.

**Comment by penge** [comment]
Permissions required by the extension:

```
"permissions": ["storage", "contextMenus", "tabs"],
```

Location: https://github.com/penge/my-notes/blob/master/manifest.json#L8

What are these permissions needed for:

## "storage"

**"storage"** permission is used to save the notes and options (font size, font type, etc.) to Chrome Storage Local, and to save selection (only in case of Save selection to other devices) to Chrome Storage Sync.

Locations:
- https://github.com/penge/my-notes/blob/master/notes.js
- https://github.com/penge/my-notes/blob/master/options.js
- https://github.com/penge/my-notes/blob/master/background.js

What to look for:
- Anything that starts with `chrome.storage.local`
- Anything that starts with `chrome.storage.sync`

## "contextMenus"

As the name implies, this permission is used to create a Context menu.

Creating the Context menu:
- https://github.com/penge/my-notes/blob/master/background.js#L30
- https://github.com/penge/my-notes/blob/master/background.js#L86

Handling the Context menu:
- https://github.com/penge/my-notes/blob/master/background.js#L89

## "tabs"

This permission is used to replace a New Tab with My Notes.

Location:
- https://github.com/penge/my-notes/blob/master/background.js#L123

Because of this one line, I suppose:

```js
// https://github.com/penge/my-notes/blob/master/background.js#L123
chrome.tabs.update(tab.id, { url: "/notes.html" });
```

Web Store things that the extension has something to do with Browsing history, which is fucking stupid.

**Comment by penge** [comment]
imho, to be honest, I would hesitate to install something that has something to do with Browsing history which are usually antivirues, ad blockers, malwares, data and privacy scrapers and that kind of thing
