### ISSUE TITLE
404 in chrome store

### ISSUE THREAD

**Issue by JeromeDeLeon** [penge/my-notes#67]
The site that you have provided is not found in chrome store.

**Comment by penge** [comment]
Finally!

So, here's what happened in the last days. On February 24th I've decided to unpublish My Notes from Web Store. Since then I was communicating to Web Store Support regarding their not publishing of version 2.3.1 for many days, which stopped 2.3.2 to get published too.

It was close My Notes might not come back if the communication with Web Store Support might not go well, or go forever.

The reason why I've decided to unpublish My Notes for a moment was due to the following:

Version 2.3.0 contains optional new tab replacement, that can open My Notes in every new tab if allowed. This needs **"tabs"** permission to work. Unfortunately, Web Store interpreted this in a very invasive `It can: Read your Browsing history` which is false statement anyway. More to it here:
- https://github.com/penge/my-notes/releases/tag/2.3.1
- https://github.com/penge/my-notes/issues/61
- https://github.com/penge/my-notes/issues/60#issuecomment-586094202

Because of `It can: Read your Browsing history`, there was a noticeable increase in the number of uninstallations. My Notes had around 400 users since December 2019 and this number was stable. I thought with 2.3.0 I can give it some new push, next marketing. That all had to wait. For all those months, 400 was a stable number, + / - only 1%, which is 3 new users, 3 users go. Because of the ugly message as mentioned, users count dropped by 20%, which is down by 80 users to 320.

Quite a terrible experience for me as a creator when I could do nothing about it. My next day fixes were in review 2 weeks and that was it. I took My Notes down. And started communicating with the support.

The next reason, more important one, why I had to unpublish My Notes temporarily, is because version 2.3.0 had a bug that affected every new user. More to it here:
- https://github.com/penge/my-notes/releases/tag/2.3.2
- https://github.com/penge/my-notes/pull/63

None of this unpublish/republish would have to happen if the approval of a PENDING REVIEW wouldn't have taken for SOOOOO LONG. You can read more about this here:
- https://news.ycombinator.com/item?id=21990566

I knew my hands are tied and while waiting for 2.3.1 to be published, I could do nothing. Cannot change the description, cannot speed it up, cannot publish 2.3.2 while 2.3.1 is still pending.

The only quick choice I had at that moment, while maintaining some level of quality, meaning I don't leave 2.3.0 out there for weeks to come while 2.3.1 and 2.3.2 provide a fix and are long-time ready, was to unpublish My Notes and start my communication with the Web Store Support, which as said, started on 24th February.

The good news is, now on March 3rd after 18 days long of waiting, My Notes 2.3.1 and right after 2.3.2, were published.

My Notes 2.3.1 and 2.3.2 were published 18 days later as they should be. You can see that here:
- https://github.com/penge/my-notes/releases

What I try to do, is to get the status of a trusted developer. This would help a lot and I am not sure if it is possible. The support line I was communicating to is here: chromewebstore-dev-support@google.com

What can help to have that kind of benefit, I guess, might be good reviews, writing to chromewebstore-dev-support@google.com even as a user who would like My Notes to be approved quicker.

My Notes development will continue which is a good thing. I'll try to make some channel for announcements and something that could user open via Options page to get here somewhere, easily, or a chat, and express their thoughts.

I have also decided that to support the development a bit, I will provide My Notes 3 as a paid version and also a free version. The free version will be having all the features it has and will continue to grow in features. Pro version will have Google Drive support. It is something I need to think about more. I'd like to ask the users about it.

**Comment by JeromeDeLeon** [comment]
You've been through a lot I must say. Thanks for opening it up. I opened this issue because I was about to recommend it to my friend when she saw about it because of it's simplicity and easy to take notes but when she visited it on the chrome store, it was nowhere to be found. Anyway, I'm glad to help you out. If it's anything I can do, just tell me. :smile:

About the pro version, I was a bit hesitant about it because this app exists because of how easy it is to take notes, but the idea is great. Maybe its just me. Who knows? :thinking: 

Thanks for the hard work! :+1:

**Comment by penge** [comment]
Thanks for recommending!

She can finally click:

![button](https://user-images.githubusercontent.com/907255/75783876-94ed1e00-5d61-11ea-9e06-88a726192278.png)


😁👍

<br><br><br>

My Notes and My Notes **Pro** would look and behave the same.
**Pro** would allow to backup to Google Drive. This would be as a checkbox in the Options page.

I know how can you help! 😉 You can join testing of My Notes 3 :)
What it will give you, as a tester, is access to the latest and also Pro version.
**https://bit.ly/hellopenge** --> here is Slack where it can be organized once the time comes

**Comment by penge** [comment]
Not an issue anymore.
