### ISSUE TITLE
Does not open with new tab anymore - v 2.3.2

### ISSUE THREAD

**Issue by lambdamusic** [penge/my-notes#68]
After updating to version 2.3.2 I can't get MyNotes to appear when I open a new tab. 

Was there a setting before?

**Comment by penge** [comment]
Yes. This has changed in 2.3.1 – https://github.com/penge/my-notes/releases/tag/2.3.1

Since 2.3.0:
My Notes can be open with **1 click on the icon** (located in the browser's toolbar)

Why _Replace New Tab_ (checkbox in Options) was removed in 2.3.1:
- https://github.com/penge/my-notes/releases/tag/2.3.1
- https://github.com/penge/my-notes/issues/61
- https://github.com/penge/my-notes/issues/60
- https://github.com/penge/my-notes/issues/67

<br>

A question for you and also everybody else reading.
Do you miss the feature of automatically opening My Notes in every new tab? Or you find **1 click on the icon** to be better?
I could try to reimplement it as an optional permission and hopefully avoid the troubles that happened before.

**Comment by lambdamusic** [comment]
Ah .. sorry for missing this from the release notes. 

I personally miss the feature. But you're the best person to judge whether it's worth the effort!

**Comment by penge** [comment]
Thanks, I personally don't miss the feature as I am a fan of having clean new tab and prefer the 1 click on the icon instead.

Nevertheless being said, I would like to support both ways if possible (replace new tab, click the icon). I just didn't anticipate there would be such miss-interpretation in Web Store (`It can: Read your Browsing history`) and quite trouble to get next version published - took 3 weeks to publish 2.3.1.

I would try to add this back in the future and have it require "tabs" as an "optional permission" instead. What that would possibly do is, the *message should not be shown when installing from Web Store but only when enabling the feature in Options once installed.

*message - As said, the message is `It can: Read your Browsing history`. This is quite hard to explain or argue because Web Store is the authority user expects to trust first.

I'll try to talk to Web Store Support more about this. There was indeed, a justification page where I had to explain new permissions required by the extension. In the end, it was ignored (or it is what it is and *message cannot be changed) and caused lot of trouble.

**Comment by penge** [comment]
I have tried to define "tabs" as optional permission.

Optional permission means it can be requested once the extension is installed to provide some additional functionality. In this case that would be requesting "tabs" permission that is needed to automatically open My Notes in every new tab.

Optional permission can be granted or denied. If granted, functionality is turned on. If denied, nothing happens.

Optional or NON-optional permission?
If something is essential and most likely will be needed, it can be NON-optional. NON-optional permission is required directly in Web Store.
The message is in both cases (optional permission, NON-optional permission) the same.

Here is a message that would be shown if you would let's say click the checkbox **Open My Notes in every new tab**:

<br>

![permission](https://user-images.githubusercontent.com/907255/76521705-a4591f00-6465-11ea-92a5-1426c2f62b28.png)

It is unfortunate this particular permission ("tabs" in this case) is shown like this.

Would you click Allow or would you hesitate?

**Comment by lambdamusic** [comment]
Knowing what the add on does and what feature I want, I'm ok to click yes.. but if I have to put myself the in shoes of a brand new user, I would hesitate I think. 

Would it help if you explain clearly in the docs the reason for this extra popup? 

I think there's value in being transparent with your users. So as long as people know what's happening, the 'optional permissions' solution could be the best solution (technical considerations aside).

**Comment by penge** [comment]
The message which we would like to see, is:

![warning](https://user-images.githubusercontent.com/907255/76645739-df3c7f00-6559-11ea-9cc3-7e4de1073fdd.png)

This message is only displayed when replacing new tab is **not** optional, or in other words, it has to happen. That's how it worked before the version 2.3.0 when My Notes was open in every new tab.

**"tabs"** permission was used in 2.3.0 (and removed in 2.3.1) to achieve **optional** new tab replacement. That means, to support both:
A) can have My Notes in every new tab
B) can have default (unchanged) new tab

I would like to support both A and B, or none.

Because **"tabs"** permission is more powerful, an unrelated message **Read your browsing activity** has been shown although the extension had nothing to do with it.

The message that comes with **"tabs"** permission was denied by every 1 of 5, that's 20% which is quite a lot. If the message would be shown once the functionality is enabled in Options, I don't think this would come down to 0.

There is a trick how **"optional"** behavior can be achieved without **"tabs"** permission by doing a redirect. It would be a redirect to either My Notes or Chrome's default new tab page located at `chrome-search://local-ntp/local-ntp.html`. I have to say this doesn't look nice because it causes the Title to jump from "chrome..." to "New Tab" or from "chrome..." to "My Notes".

**Closing.**

**Comment by penge** [comment]
I will add this back in 2.4. I hope everything will turn out well...

**Comment by penge** [comment]
2.4 is in Pending review for 5 hours now.

This publishing is sooo unpleasant.

<br>

It took 3 weeks to publish 2.3.2.

Here's a screenshot from today:

![pending](https://user-images.githubusercontent.com/907255/76710919-b0660a80-670b-11ea-831f-40c586cbf0e8.png)
