### ISSUE TITLE
Publish to Firefox addon store

### ISSUE THREAD

**Issue by lfkeitel** [penge/my-notes#7]
I tested with Firefox and the extension appears to work without any problems. The only change you'll need is to add a gecko id in the manifest.json file.

**Comment by penge** [comment]
Thanks for info. Firefox is really demanded and I am planning to put it out.
There is a common API that should allow to make it work in every big browser.

It starts with manifest, as you say, and then it's either chrome.* or browser.*

Will check it out. It's on the list.

**Comment by penge** [comment]
Giving this priority. It's next on the list.

**Comment by lfkeitel** [comment]
The chrome APIs will work in Firefox. Firefox provides the chrome API that wraps the browser API. No code changes should be needed.

**Comment by penge** [comment]
@lfkeitel I feel the same. API code is based on **WebExtensions API,** and that's a cross-browser extensions platform. There may be needed some browser-specific changes, _but mostly not._ The same would apply to browser-specific _optional_ attributes.

I am unfortunately unable to test this right now because I use Chromebook as my main device and have no access to PC or Mac at this point. The good news is, one of the users of **"stop-social-media"** wrote to me, it is working in his Firefox, besides the fact I have made no specific changes to the code. I was gladly surprised.

Before publishing it to the Firefox store, I'd like to test it out at least and not take the risk. It is not only about if the plugin works visually but also checking if there are no silent errors.

Even when at this point the extension might work flawlessly in Firefox, installing it from https://addons.mozilla.org is desirable. Until it's tested, we need to wait before publishing it.

**Comment by penge** [comment]
Closing due to the limited support in Firefox:

- `identity` permission not supported (specific to Chrome)
- `oauth2` property not supported (specific to Chrome)
- event pages are not currently supported (only persistent background pages)
- JavaScript modules are not loaded
