### ISSUE TITLE
Unable to use Tab in editor

### ISSUE THREAD

**Issue by bhupesh-sf** [penge/my-notes#82]
I am trying to use tab in editor and can't do so. While taking notes its normally required.

Can we fix that?

**Comment by penge** [comment]
**Yes, definitelly.** **I will add this to next version.**

<br><br>

## Details

This feature was here before — **Forward Tab**, and even **Backward Tab**.

**But there was a problem** — behaved **"buggy"** (not really a _bug_, just reached the limits of `textarea`) — coudn't calculate (only estimate through a series of hacks, but that wasn't precise) where the line ends. This was an unclear variable (based on font size, font width, width of the screen). Because of this, pressing `Tab` at the end of line would visually do nothing, but on refresh, the cursor would end somewhere on the next line. **Backward Tab** wasn't limited this way, as the beginning of line was always known.

Now, there are no limitations (I hope!). So can add the feature.

**Comment by bhupesh-sf** [comment]
When is the next version, sorry for being impatient ;)

**Comment by penge** [comment]
Great to hear, I'll be cheching this soon after I finish 3.0.2.
There is a conflict though, with this https://github.com/penge/my-notes/issues/58. Either Tab can jump between address bar and note nicely, or it inserts 2 whitespaces. To support both options, one more key would need to be pressed, but that makes it quite unconventional.. mm

**Comment by penge** [comment]
**Update:** I'd like to support both options (one option being `Tab` to jump between note and address bar, and second option, `Tab` inserts 2 whitespaces.) Unfortunately same `Tab` key cannot be used for both.

**Possible solutions:**

-  **A)** There would have to be one more key added, to differentiate the actions. Single `Tab` cannot do both jobs. `Tab` is also reserved for keyboard navigation.
- **B)** An option in Options that would "sacrifice" one behavior in favor of the other. That would mean, saying the role of `Tab` key (either whitespace, or nagitation).

@bhupesh-sf 
What do you think? If having only 1 behavior (option B) doesn't concern you, it would be a solution.

**Comment by bhupesh-sf** [comment]
@penge I think I am perfectly fine with option B. To me writing content in friendly way is more important than the navigation. So sacrificing behvior is fine with me.

**Comment by penge** [comment]
@bhupesh-sf Having some questions.

Is your content a source code, or **also something different** where you would need Tab to insert whitespaces?

Tab would insert **2 whitespaces**. Would you prefer 4? or both options?

Should the Tab setting be remembered on every next visit?

**Comment by bhupesh-sf** [comment]
Hey, being ambitious yes all these options makes perfectly sense. Source code is not something I care as of now but that was something a request I was about to put for future. As this has become THE TOOL for my all kind of note taking activities, so gradually wants it to evolve to fulfill those needs.

Regarding your toolbar option, that makes most sense to me. Rest others can also comment or suggest.

**Comment by penge** [comment]
@bhupesh-sf Tab could be soon and it would have same behavior as in TextEdit, or other. It is now more about where to put the toggle (option) to switch the behavior of the Tab.

**Comment by penge** [comment]
Moving this to a sooner release.

**Comment by penge** [comment]
<img width="654" alt="Screen Shot 2020-05-27 at 4 55 29 PM" src="https://user-images.githubusercontent.com/907255/83036438-e5aba480-a03a-11ea-97e6-211e26069077.png">

@jmaicaaan @bhupesh-sf  @JeromeDeLeon Hey guys! Do you like this? It can be like this.
`3.0.3` would have some great changes (content alignment, a keyboard shortcut to quickly 
 open Options and change anything, and this, Tab key function)

**Comment by bhupesh-sf** [comment]
@penge Seems good to me although option in toolbar could have been more handy.

**Comment by penge** [comment]
@bhupesh-sf I was checking that option as well. Didn't like the button was always highlighted. I'll post here a screenshot shortly. We can check that solution and compare.

**Comment by penge** [comment]
<img width="1425" alt="Screen Shot 2020-05-27 at 5 12 46 PM" src="https://user-images.githubusercontent.com/907255/83038562-65d30980-a03d-11ea-8393-ba9c40606cbc.png">

Here's a button in the toolbar for comparission.

**Comment by jmaicaaan** [comment]
I think putting it on the Settings page is great already. No need to add it on the toolbar on the main page because I find it unnecessary. And I don't think most of the users will toggle them in like the formatting options right? 😄 
Then I think making it enable by default is also better user experience!

**Comment by bhupesh-sf** [comment]
I am fine with either. Thanks for good work.
