### ISSUE TITLE
Lost text format

### ISSUE THREAD

**Issue by wbeirigo** [penge/my-notes#84]
When the version was update, I lost my text new line.
How to recover my text?

**Comment by penge** [comment]
Hi, here are the steps:

1. Open the note
2. Backup the note
3. Open **Chrome Developer Tools** (Menu / More Tools / Developer Tools)
4. Paste into the **Console**:

```js
content.innerHTML.split("\n").map(line => line + "<br>").join("");
```

5. Check if the printed result is **OK** — looks like note, just with the correct linebreaks 

6. If previous **OK**, then, put into the **Console**:

```js
content.innerHTML = content.innerHTML.split("\n").map(line => line + "<br>").join("");
```

7. The note is now updated. And looks as it should. Now press **Enter** at the end to save it.

Sorry for the complication. I hope the steps weren't too complicated. This is due to the problem in migration.

**Comment by penge** [comment]
@wbeirigo My Notes 3.0.1 that fixes this issue is now in review. Should be on Web Store shortly.
